LingCoder/OnJava8

docs/book/14-Streams.md

# 第十四章 流式编程 ## 流创建部分内容

---

docs/book/14-Streams.md

更新 Ranges of int 和 generate() 小节

更新 第十四章 流式编程：Ranges of int 和 generate() 小节

---

docs/book/14-Streams.md

第十四章 iterate() 、Stream Builders、Arrays翻译

第十四章 iterate() 、Stream Builders、Arrays翻译

---

docs/book/14-Streams.md

14章流创建小节翻译完成

---

docs/book/14-Streams.md

14章：流中间操作小节翻译完成

---

docs/book/14-Streams.md

14： Optional 小节翻译完成

---

docs/book/14-Streams.md

终于第14章翻译玩了。里面还有很多句子我翻起来非常拗口
校对的时候多多费心~

14 张最后两小节翻译完成

---

docs/book/Appendix-Data-Compression.md

附录：数据压缩翻译完成

---

docs/book/17-Files.md

翻译17章2，3两节

---

docs/book/05-Control-Flow.md

本章也属于编程语言的基本内容，翻译得很棒，在此之上，我仅做了些许校对。流程控制语句这块比较新颖的概念：
1）label的使用，算是goto的一种翻版，起跳转的作用，在开发中使用得较少
2) for-in 语法糖 在许多现代编程语言中都有其身影

[modify 05](截至 第5章结束)

---

docs/book/06-Housekeeping.md

假期断了节奏，明日恢复。这部分内容包括：
1）this 关键字，特别是在 构造器 中的使用
2）方法重载的判别方法

[feast 06](添加第6章翻译，截至 垃圾回收器)

---

docs/book/17-Files.md

add cp 9.4

---

docs/book/22-Enumerations.md

22 章枚举翻译更新

---

docs/book/12-Collections.md

第十二章 集合 翻译更新至List

---

docs/book/12-Collections.md

第十二章 集合 翻译更新至 堆栈Stack

---

docs/book/12-Collections.md

第十二章 集合 翻译更新至 队列Queue

---

docs/book/Appendix-Understanding-equals-and-hashCode.md

Part translation of Appendix-Understanding-equals-and-hashCode.md

Translation Commit

---

docs/book/17-Files.md
docs/book/24-Concurrent-Programming.md

The Rest of the Chapter and files

---

docs/book/Appendix-Collection-Topics.md

附录：集合主题 翻译更新至示例数据

---

docs/book/Appendix-Low-Level-Concurrency.md

附录：并发底层原理 翻译至volatile 关键字 - 字分裂小节

---

SUMMARY.md
docs/book/Appendix-Collection-Topics.md

附录：集合主题 翻译更新至 集合功能

---

SUMMARY.md
docs/book/Appendix-Low-Level-Concurrency.md

附录：并发底层原理 翻译至原子性开篇

---

docs/book/Appendix-Low-Level-Concurrency.md

附录：并发底层原理 翻译至原子类

---

docs/book/Appendix-Collection-Topics.md

附录：集合主题 翻译更新至 可选操作

---

docs/book/Appendix-Low-Level-Concurrency.md

附录：并发底层原理 翻译至临界区

---

docs/book/Appendix-Collection-Topics.md

附录：集合主题 翻译更新至 Set和存储顺序

---

docs/book/21-Arrays.md

Signed-off-by: cogitates <weifengzxq@gmail.com>
#117

onjava8 第二十一章 数组 第二节 一等对象

---

docs/book/Appendix-Collection-Topics.md

附录：集合主题 翻译更新至 队列

---

docs/book/Appendix-Collection-Topics.md

附录：集合主题 翻译更新至 理解Map

---

docs/book/Appendix-Collection-Topics.md

附录：集合主题 翻译更新至 集合工具类

---

README.md
SUMMARY.md
docs/book/Appendix-Collection-Topics.md

附录：集合主题 翻译完成

---

docs/book/22-Enumerations.md

第二十二章 枚举类型

---

docs/book/21-Arrays.md

Signed-off-by: cogitates <weifengzxq@gmail.com>

Fix issue #117 数组部分  第三，第四小节

---

docs/book/16-Validating-Your-Code.md

Issue #223

---

docs/book/21-Arrays.md

#117
Signed-off-by: cogitates <weifengzxq@gmail.com>

Fix issue 117, 翻译数组部分 五，六，七三个小节

---

docs/book/Appendix-Object-Serialization.md

附录：对象序列化 翻译

---

docs/book/20-Generics.md

翻译元组类库子小节，参考《Java编程思想》中文第四版，如有错误请指正，谢谢！

泛型 - 简单泛型小节

---

docs/book/20-Generics.md

翻译 堆栈类 和 RandomList 子小节，自此简单泛型小节翻译完成。

泛型 - 简单泛型小节翻译完成

---

docs/book/12-Collections.md

Update 12-Collections.md 修复原文勘误

---

docs/book/21-Arrays.md

Signed-off-by: cogitates <weifengzxq@gmail.com>

Fix issue #117 翻译数组部分 第八，第九，第十小节

---

docs/book/19-Type-Information.md

Fix issue #28: 翻译类型信息部分 动态代理小节

第十九章 类型信息 动态代理

---

docs/book/06-Housekeeping.md

第六章-重载与基本类型的示例代码中，补充了long类型在重载时的结果。

Update 06-HouseKeeping.md 补充示例代码中缺少的long类型

---

docs/book/21-Arrays.md

数组元素修改和数组并行小节完成，不知道翻译的如何，如果有错误请指教

数组元素修改和数组并行小节完成

---

docs/book/17-Files.md

revision[17] 结束

---

docs/book/19-Type-Information.md

issue：#28 
- 第19章**翻译完成**
- 调整了一下第19章的代码格式

第19章 类型信息 翻译完成

---

docs/book/Appendix-IO-Streams.md

附录:流式IO 翻译完成

---

SUMMARY.md

修正第五章控制流 第一子节 'true和false'标题中错误拼写
close #439

修正第五章错误小节标题

---

README.md

Fix README.md 样式：
- 英文字符与中文字符连接处添加空格
- 去除行末多余空格
- Fix 列表缩进导致的样式问题

Fix README.md 样式

---

docs/book/15-Exceptions.md

DymamicFields 改为 DynamicFields .

修正一个单词拼写错误

---

docs/book/14-Streams.md

删除第14章多出的一段

---

docs/book/Appendix-Standard-IO.md

correct a word

---

docs/book/18-Strings.md
docs/book/20-Generics.md

- 第十八章 字符串 
WitherStringBuilder -> WhitherStringBuilder
- 第二十章 泛型 
ComparableSet -> ComparablePet

第十八章&第二十章 类名错误

---

docs/book/22-Enumerations.md

fix(doc):修改错别字

---

docs/book/12-Collections.md

将“继承再AbstractCollection” 修改为再继承

将“继承再AbstractCollection” 修改为再继承

---

docs/book/04-Operators.md

04-Operators.md 497行  注释的二进制代码不对吧

10101111改为01111111

---

docs/book/24-Concurrent-Programming.md

第24章 并发编程 代码关键字中间增加空格

---

docs/book/25-Patterns.md

错误换行导致代码格式出现问题
参照https://github.com/sjsdfg/OnJava8-Examples-Maven/blob/master/patterns/src/main/java/TemplateMethod.java
代码进行修复

修复25章-模板方法模式中的代码格式问题

---

docs/book/24-Concurrent-Programming.md

* 并行流模块
> Java 8 流的一个显著优点是，在某些情况下，它们可以很容易地并行化。这来自仔细的库设计，
最后一句改为 **这来自库的仔细设计** 
* newIntGenerator()改为new IntGenerator()

修改24章并发编程代码问题
